apiVersion: v1
kind: Service
metadata:
  name: hela-gitlab
  labels:
    app: gitlab
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
  - name: https
    protocol: TCP
    port: 443
  - name: ssh
    protocol: TCP
    port: 22
  selector:
    app: gitlab
    tier: backend
  type: LoadBalancer